<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-03-05T12:45:11 IST" name="Suite" finished-at="2023-03-05T12:45:27 IST" duration-ms="15752">
    <groups>
    </groups>
    <test started-at="2023-03-05T12:45:11 IST" name="Test" finished-at="2023-03-05T12:45:27 IST" duration-ms="15752">
      <class name="testClasses.Calculator_TestClass">
        <test-method is-config="true" signature="browserLaunch(java.lang.String)[pri:0, instance:testClasses.Calculator_TestClass@3f4faf53]" started-at="2023-03-05T12:45:11 IST" name="browserLaunch" finished-at="2023-03-05T12:45:16 IST" duration-ms="5038" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserLaunch -->
        <test-method signature="TC_01_Multiplication()[pri:0, instance:testClasses.Calculator_TestClass@3f4faf53]" started-at="2023-03-05T12:45:16 IST" name="TC_01_Multiplication" finished-at="2023-03-05T12:45:17 IST" duration-ms="360" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_01_Multiplication -->
        <test-method is-config="true" signature="clear(org.testng.ITestResult)[pri:0, instance:testClasses.Calculator_TestClass@3f4faf53]" started-at="2023-03-05T12:45:17 IST" name="clear" finished-at="2023-03-05T12:45:19 IST" duration-ms="2085" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=TC_01_Multiplication status=SUCCESS method=Calculator_TestClass.TC_01_Multiplication()[pri:0, instance:testClasses.Calculator_TestClass@3f4faf53] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clear -->
        <test-method signature="TC_02_Division()[pri:0, instance:testClasses.Calculator_TestClass@3f4faf53]" started-at="2023-03-05T12:45:19 IST" name="TC_02_Division" finished-at="2023-03-05T12:45:19 IST" duration-ms="314" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [ 200] but found [ 20]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [ 200] but found [ 20]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at testClasses.Calculator_TestClass.TC_02_Division(Calculator_TestClass.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_02_Division -->
        <test-method is-config="true" signature="clear(org.testng.ITestResult)[pri:0, instance:testClasses.Calculator_TestClass@3f4faf53]" started-at="2023-03-05T12:45:19 IST" name="clear" finished-at="2023-03-05T12:45:21 IST" duration-ms="2275" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=TC_02_Division status=FAILURE method=Calculator_TestClass.TC_02_Division()[pri:0, instance:testClasses.Calculator_TestClass@3f4faf53] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clear -->
        <test-method signature="TC_03_Addition()[pri:0, instance:testClasses.Calculator_TestClass@3f4faf53]" started-at="2023-03-05T12:45:21 IST" name="TC_03_Addition" finished-at="2023-03-05T12:45:22 IST" duration-ms="551" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [ 1111110] but found [ 111111]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [ 1111110] but found [ 111111]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at testClasses.Calculator_TestClass.TC_03_Addition(Calculator_TestClass.java:54)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_03_Addition -->
        <test-method is-config="true" signature="clear(org.testng.ITestResult)[pri:0, instance:testClasses.Calculator_TestClass@3f4faf53]" started-at="2023-03-05T12:45:22 IST" name="clear" finished-at="2023-03-05T12:45:24 IST" duration-ms="2256" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=TC_03_Addition status=FAILURE method=Calculator_TestClass.TC_03_Addition()[pri:0, instance:testClasses.Calculator_TestClass@3f4faf53] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clear -->
        <test-method signature="TC_04_Subtraction()[pri:0, instance:testClasses.Calculator_TestClass@3f4faf53]" started-at="2023-03-05T12:45:24 IST" name="TC_04_Subtraction" finished-at="2023-03-05T12:45:25 IST" duration-ms="589" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_04_Subtraction -->
        <test-method is-config="true" signature="clear(org.testng.ITestResult)[pri:0, instance:testClasses.Calculator_TestClass@3f4faf53]" started-at="2023-03-05T12:45:25 IST" name="clear" finished-at="2023-03-05T12:45:27 IST" duration-ms="2097" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=TC_04_Subtraction status=SUCCESS method=Calculator_TestClass.TC_04_Subtraction()[pri:0, instance:testClasses.Calculator_TestClass@3f4faf53] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clear -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:testClasses.Calculator_TestClass@3f4faf53]" started-at="2023-03-05T12:45:27 IST" name="teardown" finished-at="2023-03-05T12:45:27 IST" duration-ms="128" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- testClasses.Calculator_TestClass -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
